### ISSUE TITLE
Make REST GW config reusable

### ISSUE THREAD

**Issue by smallhive** [nspcc-dev/neofs-testcases#1034]
## Is your feature request related to a problem? Please describe.
It is not possible to restart REST GW with generated config

## Describe the solution you'd like
Add to REST GW config template section with peers

```yaml
pool:
  ...
  peers:
    0:
      address: localhost:<node1_port>
      priority: 1
      weight: 1
    1:
      address: localhost:<node2_port>
      priority: 1
      weight: 1
    2:
      address: localhost:<node3_port>
      priority: 1
      weight: 1
    3:
      address: localhost:<node4_port>
      priority: 1
      weight: 1
...
```

## Describe alternatives you've considered
No options

## Additional context
During debugging, it is useful to stop, update and restart the gate. Without it, the YAML config must be edited manually each `--perist-env` session
