### ISSUE TITLE
Metabase resync test is not compatible with node 0.46.0

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-testcases#1051]
## Current Behavior
https://rest.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/3166-1745943519/index.html#suites/4b9f0852769b4f47c7f6f0b89053e5e7/c3b7d5cc897aaba8/

## Expected Behavior
Green.

## Possible Solution
`NEOFS_STORAGE_SHARD_{idx}_RESYNC_METABASE` variable is not correct, it's `NEOFS_STORAGE_SHARDS_{idx}_RESYNC_METABASE` now. But we also use the same prefix in `pytest_tests/tests/shard/test_control_shard.py` and it should be version-dependent, so needs to be untangled.

## Steps to Reproduce
Run testcases with master (pre-0.46.0) node.

## Context
https://github.com/nspcc-dev/neofs-testcases/pull/1003

**Comment by roman-khimov** [comment]
Likely related to https://rest.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/3166-1745943519/index.html#suites/332cda9b41c660da86afd05b5e4a4a4d/3794e554f7880629/ as well.

**Comment by evgeniiz321** [comment]
@roman-khimov if I set env variable - `NEOFS_STORAGE_SHARDS_{idx}_RESYNC_METABASE` i got:
```
2025/05/12 14:26:42 metabase at shard 0 has empty path
```
Even though metabase path exists in the config:
```
storage:    
  shards:
    - writecache:
        enabled: False
        path: /Users/evgeniiz/Projects/neofs-testcases-nspcc/neofs-testcases/test-run-2025-05-12-18-25-12-215052/env_files/neofs-env-2025-05-12-18-25-13/shards/shard_wc_qaqysejmfk  # Write-cache root directory

      metabase:
        path: /Users/evgeniiz/Projects/neofs-testcases-nspcc/neofs-testcases/test-run-2025-05-12-18-25-12-215052/env_files/neofs-env-2025-05-12-18-25-13/sn_1_jjspjkusfg/shard_metabase_daeefbzvte  # Path to the metabase

      blobstor:
        type: fstree
        path: /Users/evgeniiz/Projects/neofs-testcases-nspcc/neofs-testcases/test-run-2025-05-12-18-25-12-215052/env_files/neofs-env-2025-05-12-18-25-13/shards/shard_fstree_onlhlpquic  # FSTree root directory
        depth: 2
```
If i set `resync_metabase` via config - works ok. Is it an expected behavior? Do I need to configure everything either via env vars or via config but not both at the same time?
