### ISSUE TITLE
Test IR change with main chain role change

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-testcases#943]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when we don't have tests for some core NeoFS things.

## Describe the solution you'd like
Test IR change in 4-node IR scenario with main chain. IR is controlled by the designation contract on main chain, it's the same as IR set initially, but main chain committee can set it to any other list of nodes and FS chain must follow this change. IR includes CNs, both change in this setting.

## Additional context
https://github.com/neo-project/neo/issues/2267

**Comment by evgeniiz321** [comment]
@roman-khimov questions:
1. how to get the hash of the designation contract?
2. as far as I understand I need to invoke `designateAsRole` function, but with what arguments? (`designateAsRole int:16 [ {keys_str} ]  -- {script_hash}` ? )
3. from IR side - how can I check that fs chain reflected the state of the designation contract (and how soon this can happen? next epoch?)

**Comment by roman-khimov** [comment]
1. 0x49cf4e5378ffcd4dec034fd98a174c5491e395e2
2. Yes, it's an ID of role and an array of keys. Signed by the committee (in your case it should 1/1 for the main chain since you only have one validator).
3. Get the committee from FS chain, check for logs. Not sure IR exports any metrics for it. neo-exported technically does it. IIRC it can take an epoch, but let's check.

**Comment by evgeniiz321** [comment]
@roman-khimov need to clarify a change scenario a little bit, cause I'm keep getting ```error   governance/process_update.go:39 can't merge alphabet lists from main net and FS chain   {"error": "alphabet list in mainnet is too short: expecting 4 keys"}``` after the change.

We need to deploy main chain + 4 IR nodes. And what should be the next step? Cause I tried to shrink the list of alphabet nodes specified here:
```
  Genesis:
    Roles:
      NeoFSAlphabet:
        - 0227dd679578bf007125c6d780166fdeb52dcd9746a757ec2ca42182b9d3da21cd
        - 0251f6575bb537dd9f284199c2302a7a0375fadf94a411002b332b13c6971bc28d
        - 027f3bb44854b91648b20f80f9c3fb808cb07766d0d92764800bf2a8c3b2d7af12
        - 02b22315a6402195be1dc6ac6976c2d99190f17f6891b6625eb728d17ece8fc79a
```
But seems like it is not allowed. Then I tried to specify 3 nodes in the list above, but ```"alphabet list in mainnet is too short: expecting 4 keys"```started to appear at the startup of IRs. After adding 4th node I got ```no governance update, alphabet list has not been changed```. 

Also can you point me to the right command to check the list of designated roles? both from main chain and fs chain. For the main chain I tried to use:
```
./neo-go contract invokefunction --rpc-endpoint 'http://localhost:59400' --await --force --wallet-config 'wallet-config.yaml' 0x49cf4e5378ffcd4dec034fd98a174c5491e395e2 getDesignatedByRole int:16 3725
```
But it doesn't return a list of pubkeys.
